security:
    providers:
        players:
            entity: { class: MVSB\MyVirtualStoryBookBundle\Entity\Player, property: username }
    encoders:
        MVSB\MyVirtualStoryBookBundle\Entity\Player: sha512
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        api:
            pattern:    ^/
            mvsb: true
            stateless: false
        default:
            anonymous: ~