<?php

namespace MVSB\MyVirtualStoryBookBundle\Repository;

use MVSB\MyVirtualStoryBookBundle\Entity\Player;
use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository{
    
    public function addPlayerToBase(Player $player){
        $em = $this->getEntityManager();
        $em->persist($player);
        $em->flush();
    }
}
