mvsb_my_virtual_story_book_player:
    resource: "@MVSBMyVirtualStoryBookBundle/Controller/PlayerController.php"
    type:     annotation
mvsb_my_virtual_story_book_book:
    resource: "@MVSBMyVirtualStoryBookBundle/Controller/BookController.php"
    type:     annotation
mvsb_my_virtual_story_book_page:
    resource: "@MVSBMyVirtualStoryBookBundle/Controller/PageController.php"
    type:     annotation