services:
#    mvsb_my_virtual_story_book.example:
#        class: MVSB\MyVirtualStoryBookBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
##########################REPOSITORY#########################
    mvsb.player.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Player
    mvsb.page.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Page    
    mvsb.genre.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Genre
    mvsb.book.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Book
    mvsb.transition.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Transition
    mvsb.game.repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments:
            - MVSB\MyVirtualStoryBookBundle\Entity\Game
#######################BUILDER############################
    mvsb.book.builder:
        class: MVSB\MyVirtualStoryBookBundle\Builder\BookBuilder
        arguments: []
    mvsb.page.builder:
        class: MVSB\MyVirtualStoryBookBundle\Builder\PageBuilder
        arguments: []
######################SERVICES############################
    mvsb.player.service:
        class: MVSB\MyVirtualStoryBookBundle\Service\PlayerService
        arguments: [@mvsb.player.repository, @mvsb.book.repository, @mvsb.book.builder]
    mvsb.book.service:
        class: MVSB\MyVirtualStoryBookBundle\Service\BookService
        arguments: [@mvsb.book.repository, @mvsb.genre.repository, @mvsb.page.repository, @mvsb.page.builder]
    mvsb.page.service:
        class: MVSB\MyVirtualStoryBookBundle\Service\PageService
        arguments: [@mvsb.page.repository, @mvsb.transition.repository]
######################SECURITY#############################
    mvsb.security.provider:
        class:  MVSB\MyVirtualStoryBookBundle\Security\MVSBAuthenticationProvider
        arguments: ['']
    mvsb.security.listener:
        class:  MVSB\MyVirtualStoryBookBundle\Security\MVSBListener
        arguments: [@security.context, @security.authentication.manager, @security.http_utils]